services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_RUNNERS_ENABLED=true
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=yourpassword
      - N8N_HOST=luvlang.org
      - N8N_PORT=5678
      - WEBHOOK_URL=https://luvlang.org
    volumes:
      - ${HOME}/.n8n:/home/node/.n8n

