[build]
  command = "npm run build"
  publish = "build/client"
  functions = "build/server"
  edge_functions = "build/edge-functions"  # Optional: Only if using edge functions

[build.environment]
  NODE_VERSION = "18"  # Netlify defaults to Node 16, which can cause issues
  NPM_FLAGS = "--legacy-peer-deps"
